### ISSUE TITLE
I'm not catching up the basics

### ISSUE THREAD

**Issue by tarkhil** [reefland/ansible-zfs_on_root#4]
### Ask your question

Where's zfs_on_root.yml mentioned in docs? I'm not too deep into ansible (yet) so I have some troubles writing it....

**Comment by reefland** [comment]
Sorry for the delay...  it just calls the role:

```
---
- name: ZFS on Root Ubuntu Installation
  hosts: zfs_on_root_install
  become: true
  gather_facts: true

  roles:
    - role: zfs_on_root
```
