### ISSUE TITLE
There is ansible.builtin.replace module for grep + sed shell commands

### ISSUE THREAD

**Issue by Adito5393** [reefland/ansible-zfs_on_root#5]
https://github.com/reefland/ansible-zfs_on_root/blob/f51ebe3b7262d05f26ac111d2feb3e3bd50d40aa/tasks/19_final_setup.yml#L173

I've replaced this shell command with the following Ansible [replace module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/replace_module.html#examples), maybe you are interested in using it also:

```yml
- name: Disable the log compression in each file so ZFS does the Log Compression
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: (^|[^#y])(compress)
    replace: '\1#\2'
  with_items: "{{ files_matched.files }}"
  loop_control:
    label: "{{ item.path }}"
```

This way you don't have to use double dashes `//` & in my Debian shell I had to add `executable: bash` and even like that it replaced wrong... it added `\1#\2` 
Thanks for sharing your work!
